### PR TITLE
Separate workflow for scheduled update

### PR DESCRIPTION
**Pull request by f-fl0**
Scheduled workflow are automatically disabled after 60 days of inactivity (https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow). This means, it will no longer be trigger on PR for example. To prevent this situation, the scheduled update is moved to a separate workflow and rely on a reusable workflow to share the actions to perform with the on PRs/manually triggered workflow.

### CODE REVIEW

**Comment by at-wat** [comment]
> To prevent this situation, the scheduled update is moved to a separate workflow and rely on a reusable workflow to share the actions to perform with the on PRs/manually triggered workflow.

How is the situation prevented?
I think manually triggering the workflow doesn't resume disabled schedule.

**Comment by f-fl0** [comment]
I assume the scheduled update workflow will still be disabled after 60 days of inactivity but not the `on PR/manually triggered` workflow. Currently all of them get disabled.

**Comment by at-wat** [comment]
> Currently all of them get disabled.

I don't think schedule outdate affects PR and manual trigger. If so, it should be a bug of GitHub.
Master branch has no update since Jul 13 at now, but CI on your other PR was triggered and manual event trigger is available.
image

**Comment by at-wat** [comment]
I noticed you enabled scheduled workflow. Do you mean CI on PR and manual event trigger UI were disabled before that?

**Comment by f-fl0** [comment]
> I noticed you enabled scheduled workflow. Do you mean CI on PR and manual event trigger UI were disabled before that?

It seems so. It is not so obvious anymore as I rebased the branch from https://github.com/seqsense/aports-ros-updater/pull/57 but CI was not triggered when I opened it. As you said it might be a bug on Github. Something similar has been reported in https://github.com/orgs/community/discussions/32197 apparently.

If you think those changes are not necessary, I don't mind closing this PR unmerged.

**Review by at-wat — APPROVED** [review]
LGTM as a workaround of https://github.com/orgs/community/discussions/32197

**Pull request merged**
